### ISSUE TITLE
"[warning] Encountered an unknown block tag @includeExample"

### ISSUE THREAD

**Issue by johan1252** [ferdodo/typedoc-plugin-include-example#5]
If using this plugin with `typedoc`, receive warnings for all uses of `@includeExample`.

`[warning] Encountered an unknown block tag @includeExample`

**Comment by ferdodo** [comment]
I think this can be fixed by adding known block tags to the configuration with 

https://typedoc.org/api/interfaces/Configuration.TypeDocOptions.html#blockTags

And 

https://typedoc.org/api/classes/Configuration.Options.html#setValue

The current tsdoc.json only have effect on the plugin itself

**Comment by ferdodo** [comment]
![image](https://github.com/user-attachments/assets/849c9591-958f-4ada-ab1c-eb0e7eb768f9)

![image](https://github.com/user-attachments/assets/bbfe32b3-47ef-4e33-9e50-5f04b393a811)

Re-opened, I am now setting the @includeExample tag in the config and it seems it still throw some warnings.

**Comment by ferdodo** [comment]
![image](https://github.com/user-attachments/assets/ed05b752-e20a-4d9c-97ff-876c598314b4)

Fixed. You have to set options at the right moment. After the application is bootstraped (because it would be overriden?), but before the converter is initialized, because configuration is duplicated at that time.

**Comment by johan1252** [comment]
Thank you! 🙏
